services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRS_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_social_network
    ports:
      - 5432:5432
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
